config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
    # binding.pry
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy

    respond_to do |format|
      # format.html { redirect_to cats_url, notice: "Cat was successfully destroyed.", status: :see_other }
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :age)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        # redirect_to posts_path
        format.turbo_stream # create.turbo_stream.erb
        # format.turbo_stream { render turbo_stream: turbo_stream.append('posts', @post) }
      else
        # render :new
        format.html { render :new, status: :unprocessable_entity } # new.html.erb
      end
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end


  # GET /posts/1/edit
  def edit
  end


  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>">
  <p>
    <strong>Name:</strong>
    <%= cat.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= cat.age %>
  </p>

</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Show this cat", @cat %> |
  <%= link_to "Back to cats", cats_path %>
</div>

<hr>

<%= turbo_frame_tag @cat do %>
  <div>Form to edit the cat</div>
  <%# link_to 'Return to Cat', @cat, data: { turbo_frame: '_top' } %>
  <%= link_to 'Return to Cat', @cat %>
<% end %>

<%= turbo_frame_tag 'list-region' do %>
  <div>Edit cat_2!</div>
  <div><%= @cat %></div>
  <div><%= @cat.id %></div>
<% end %>

app/views/cats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cats</h1>

<div id="cats">
  <% @cats.each do |cat| %>
    <%= render cat %>
    <p>
      <%= link_to "Show this cat", cat %>
    </p>
  <% end %>
</div>

<%= link_to "New cat", new_cat_path %>

<hr>

<% @cats.each do |cat| %>
  <%= turbo_frame_tag cat do %>
    <div><%= cat.name %></div>
  <% end %>
<% end %>

<br>

<%= link_to 'Edit cat 2', edit_cat_path(Cat.find(2)), data: { turbo_frame: 'list-region'} %><br>
<%= turbo_frame_tag 'list-region' %>

<br>

<%= turbo_frame_tag 'list-region', src: edit_cat_path(Cat.find(2)) do %>
  <div>
    I am a placeholder! After the request to edit_cat_path is finished,
    I will be replaced with the content inside of that page's turbo turbo_frame
    with the id of 'list-region'.
  </div>
<% end %>

<%= turbo_frame_tag 'list-region', src: edit_cat_path(Cat.find(2)), loading: 'lazy' do %>
  <div>
    I am a placeholder! I will be replaced through lazy loading when a user scrolls down to see me on the page!
  </div>
<% end %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat), data: { turbo_method: :get, turbo_confirm: 'Edit this cat?'} %> |
  <%= link_to "Back to cats", cats_path, data: { turbo_method: :get, turbo_confirm: 'Back to cats index?' } %>

  <%= button_to "Destroy this cat", @cat, method: :delete, data: { turbo_confirm: 'Destroy this cat?'} %>
  <%= link_to "Destroy this cat", @cat, data: { turbo_method: :delete, turbo_confirm: 'Destroy this cat?' } %>
</div>

<hr>

<%= turbo_frame_tag @cat do %>
  <div>Content for our cat!</div>
  <%= link_to 'Edit Cat', edit_cat_path(@cat) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwirePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <%= post.body %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append 'posts', @post %> <%# <- turbo stream packet: action='append' target='posts' %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag id='new_post', src: new_post_path %>
<div id="posts">
  <%= render @posts %>
</div>

<div <%= tag.attributes data: { controller: 'alert' } %>>
  <button data-action='click->alert#show'>Alert me!</button>
</div>

<%= tag.div data: { controller: 'alert' } do %>
  <%= tag.button data: { action: 'click->alert#show' } do %>Alert me!<% end %>
<% end %>

<%= content_tag :div, data: { controller: 'alert' } do %>
  <%= content_tag :button, data: { action: 'click->alert#show' } do %>
    Alert me!
  <% end %>
<% end %>

<div data-controller='greeter' data-greeter-change-class='hidden'>
  <input type='text' data-greeter-target='name'>
  <button data-action='click->greeter#greet'>Greet me!</button>
  <div data-greeter-target='output'></div>
  <div data-greeter-count-value='0'></div>

  <div data-greeter-target='classDiv'>
    <button data-action='click->greeter#toggle'>Toggle class</button>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag id='new_post' do %>
  <%= form_with model: @post do |form| %>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>